version: 1.0
stages:
  - clone
  - test
  - build

steps:
  clone:
    title: Clone
    description: Clones the git repo
    type: git-clone
    stage: clone
    repo: philzona/test_app
    git: github-cf
    revision: ${{CF_REVISION}}

  test:
    title: Unit tests
    description: Execute unit tests
    type: freestyle
    stage: test
    image: alpine:latest
    working_directory: ${{clone}}
    commands:
      - exit 0 # Replace with real tests

  build_image:
    title: Build
    description: Build the image
    type: build
    stage: build
    working_directory: ${{clone}}
    arguments:
      image_name: 'phil_zona/test_app'
      tag: '${{CF_BUILD_ID}}'
      disable_push: true
      registry: quay
    when:
      branch:
        only: [main]

  push_to_quay:
    title: Push
    description: Pushes the built image
    type: push
    stage: build
    candidate: '${{build}}'
    image_name: 'phil_zona/test_app'
    registry: quay
    tags:
      - ${{CF_BUILD_ID}}
      - latest
    when:
      branch:
        only: [main]
